Apps/SplineValidations.cpp, Utils/SplineMonoUtils.cpp, Utils/SplineMonoUtils.h
Neccesary for this https://github.com/mach3-software/MaCh3/pull/92
=> Update splines validations

.github/auto_assign.yml, .github/workflows/Review.yml, README.md
=> auto assign reveiwers

CMakeLists.txt, Inputs/ManagerTest.yaml, README.md, Tutorial/CMakeLists.txt, Tutorial/MCMCTutorial.cpp, Tutorial/TutorialDiagConfig.yaml
=> First pseudo tutorial

Apps/CovarianceValidations.cpp, Apps/FitterValidations.cpp, Apps/SplineValidations.cpp, CMakeLists.txt, README.md, cmake/Modules/mach3tutorial-config.cmake, cmake/Templates/MaCh3TutorialConfig.cmake.in, cmake/Templates/mach3tutorial-config.in, cmake/Templates/setup.MaCh3Tutorial.sh.in
=> bare bone mach3 tutorial

Apps/CovarianceValidations.cpp, Apps/FitterValidations.cpp, Inputs/CovarianceOut.txt, Inputs/ManagerTest.yaml, Inputs/PCATest.yaml, README.md
=> PCA testing

Apps/CMakeLists.txt, Apps/NuMCMCconversion.cpp, Apps/NuMCMCvalidations.sh, Apps/TestNuMCMC.py
=> NuMCMC dummy converter

Apps/TestNuMCMC.py
=> Fix due ti recent hacks to NuMCMC tools

CMakeLists.txt
=> Bump MaCh3Tutorial_VERSION to 1.1.8

.github/workflows/CDImage.yml, CMakeLists.txt, Doc/DockerFiles/Alma9/Dockerfile
=> Bump MaCh3Tutorial_VERSION to 1.2.0

.github/workflows/Linter.yml, Apps/FitterValidations.cpp, CMakeLists.txt, Inputs/ManagerTest.yaml
=> Test of Factory

Apps/NuMCMCconversion.cpp, Apps/TestNuMCMC.py, CMakeLists.txt
It now works
[simpleplots.pdf](https://github.com/user-attachments/files/17450606/simpleplots.pdf)
=> Fixign NuMCMC Tool CI

Apps/FitterValidations.cpp
See https://github.com/mach3-software/MaCh3/pull/175 for more
=> Start From Previous CI

Tutorial/LLHScanTutorial.cpp, Tutorial/MCMCTutorial.cpp
See for more: https://github.com/mach3-software/MaCh3/pull/200
=> Use SamplePDF Factory

Tutorial/TutorialDiagConfig.yaml
=> Udpate config

.github/workflows/CIPythonValidations.yml, .github/workflows/CIValidations.yml, README.md
Better descirption of what is number of steps
=> Expand Tutorial

CIValidations/CMakeLists.txt, CIValidations/MaCh3CLI, CIValidations/pValueValidations.cpp, README.md
Simple SampleSummary (pvalue) was last big class which wasn't tested by CI.
=> CI for pvalue code

CIValidations/CovarianceValidations.cpp
=> Adaptive CI

Inputs/SystematicModel.yaml, samplePDF/samplePDFTutorial.cpp
Now norm params work so tutorial is more complete
=> Fix norm params in tutorial

.github/labeler.yml, CIValidations/SamplePDFValidations.cpp
Simply now start testing test stat LLH as well so Poisson, Barlo-Beeston etc
=> Test Stat CI

CMakeLists.txt
=> Bump MaCh3Tutorial_VERSION to 1.3.2

CIValidations/CovarianceValidations.cpp, CIValidations/README.md, CIValidations/TestOutputs/CovarianceOut.txt, CIValidations/UnitTests/manager_tests.cpp
Inspired by https://github.com/mach3-software/MaCh3/pull/257
=> More DetID checks

.github/workflows/CIPythonValidations.yml, .github/workflows/CIValidations.yml, .github/workflows/CodeQL.yml, CMakeLists.txt, cmake/Modules/CIValidations.cmake
Move all CI related bits to new cmake list
=> tidy: cmake build

CIValidations/MaCh3CLI, README.md
This need to be merged first: 
https://github.com/mach3-software/MaCh3/pull/271
=> tiddy: Improve Diag MCMC description

CMakeLists.txt, Utils/CMakeLists.txt, Utils/SplineMonoUtils.cpp, samplePDF/CMakeLists.txt, samplePDF/samplePDFTutorial.cpp, splines/BinnedSplinesTutorial.cpp, splines/CMakeLists.txt
Enable in tutorial Werror to make it more tidy
=> feat: Werror

samplePDF/samplePDFTutorial.h
For more see: 
https://github.com/mach3-software/MaCh3/pull/292
=> breaking: tweak func pars

.github/workflows/Linter.yml, Inputs/SystematicModel.yaml
Add review dog commenting system
=> feat: Testing good dog

samplePDF/samplePDFTutorial.cpp, samplePDF/samplePDFTutorial.h
For more see: https://github.com/mach3-software/MaCh3/pull/314
=> feat: Return Kinematic Param

Inputs/SamplePDF_Tutorial.yaml, Inputs/SamplePDF_Tutorial_ATM.yaml
Neccessary changes for 
https://github.com/mach3-software/MaCh3/compare/develop...dbarrow257/feature/BinnedOscProbOptimsations
=> feat: EqualBinningPerOscChannel

splines/BinnedSplinesTutorial.cpp
See this
https://github.com/mach3-software/MaCh3/pull/334
=> breaking: Use M3:: namespace

CMakeLists.txt
=> feat: native support

TutorialConfigs/NuOscillator/CUDAProb3.yaml
=> feat: Update CUDAProb3.yaml config to include new production height treatment

samplePDF/StructsTutorial.h
=> bugfix: Fix the CC1Pi0 mode issue in Tutorial

splines/BinnedSplinesTutorial.cpp, splines/BinnedSplinesTutorial.h
=> feat: Move StripDuplicatedSplines and GetEventSplines to splineFDBase

cmake/Templates/setup.MaCh3Tutorial.sh.in
This is to avoid no such directory message
=> bugfix: Add lib64 only if exist

CMakeLists.txt, TutorialConfigs/MaCh3Modes.yaml
=> tidy: Update MaCh3Modes

CIValidations/CMakeLists.txt, CIValidations/MaCh3CLI, CIValidations/SigmaVarValidations.cpp
All sample info is garbage, it is supposed to ensure that feature is working without segfault etc
=> feat: Sigma Var CI

TutorialConfigs/FitterConfig.yaml
Chasing mach3-software/MaCh3#383, add a commented out option for 2D llh scan number of points
=> Add commented out parameter for 2D llh scans

CIValidations/CovarianceValidations.cpp, CIValidations/FitterValidations.cpp, CIValidations/SamplePDFValidations.cpp, CIValidations/SigmaVarValidations.cpp, CIValidations/TestOutputs/CovarianceOut.txt, CIValidations/pValueValidations.cpp, CMakeLists.txt, README.md, Tutorial/KinemDistributionTutorial.cpp, TutorialConfigs/CovObjs/OscillationModel.yaml, TutorialConfigs/CovObjs/PCATest.yaml, TutorialConfigs/CovObjs/SystematicModel.yaml, TutorialConfigs/Samples/SamplePDF_Tutorial.yaml, TutorialConfigs/Samples/SamplePDF_Tutorial_ATM.yaml, samplePDF/samplePDFTutorial.cpp
There is no longer a separate DetID field in the Sample yaml, we just use the SampleName. Renamed some variables and functions accordingly.
Change to config to remove DetID
Change to some covariance function names e.g. GetParFromDetID->GetParFromSampleName
Change in parameter yaml from DetID to SampleID
=> breaking: det id fix

samplePDF/CMakeLists.txt
Use MaCh3_GPU_ENABLED instead of very confusing CPU_ONLY...
=> feat: Improve cmake

splines/BinnedSplinesTutorial.cpp
=> feat: Fix memory leak

samplePDF/StructsTutorial.h
Now propelry delete isNC and add documenation
=> feat: Fix isNC destructor

CIValidations/UnitTests/histogram_tests.cpp, CIValidations/UnitTests/manager_tests.cpp
Simply start testing if GetBounds is getting consistent results
=> feat: Yaml check bounds into CI

CIValidations/SamplePDFValidations.cpp, samplePDF/samplePDFTutorial.cpp, samplePDF/samplePDFTutorial.h
Simply start checking if shared NuOsc works. 
Warning, requeirs tweak in SamplePDF destructor to work see :https://github.com/mach3-software/MaCh3/pull/427
=> feat: Shared NuOsc CI

CIValidations/CovarianceValidations.cpp, CIValidations/FitterValidations.cpp, CIValidations/LLHValidation.cpp, CIValidations/MaCh3ModeValidations.cpp, CIValidations/SigmaVarValidations.cpp, CIValidations/SplineValidations.cpp, CIValidations/pValueValidations.cpp
CI assumed you always run from build. Not terrible but not ideal. Inputs are hardcoded eihter way becasue it must be reproducible. Let's use MaCh3Tutorial_ROOT to allow to run from any directory
=> feat: Path Independent CI

CIValidations/SamplePDFValidations.cpp, CMakeLists.txt, SamplesTutorial/SampleHandlerTutorial.cpp, SamplesTutorial/SampleHandlerTutorial.h
See https://github.com/mach3-software/MaCh3/pull/450
=> feat: Tweaks For Osc Handler

SamplesTutorial/SampleHandlerTutorial.cpp
See: https://github.com/mach3-software/MaCh3/pull/455
=> OscChannel

CIValidations/SamplePDFValidations.cpp, SamplesTutorial/SampleHandlerTutorial.cpp, SamplesTutorial/SampleHandlerTutorial.h, SamplesTutorial/StructsTutorial.h
This update turorial to work with the so called removed osicalltion channel removal
For more [with valdiations] see:  https://github.com/mach3-software/MaCh3/pull/458
=> breaking: Osc Channel Removal

CIValidations/CovarianceValidations.cpp
For more see: https://github.com/mach3-software/MaCh3/pull/464
=> tidy: Update PCA Handler Interface

.github/workflows/CIBenchmark.yml, CMakeLists.txt, Tutorial/CMakeLists.txt
This will udpate weekly output of gpe perf tools which can be viewed here:
https://github.com/mach3-software/MaCh3Tutorial/tree/gh-benchmarks
=> feat: Benchmark Bot

CIValidations/FitterValidations.cpp, CIValidations/SamplePDFValidations.cpp, CIValidations/SigmaVarValidations.cpp, CIValidations/pValueValidations.cpp, SamplesTutorial/SampleHandlerTutorial.cpp
For more see: https://github.com/mach3-software/MaCh3/pull/498
=> breaking: Update GetMC Hist

CIValidations/Benchmark/MaCh3Benchmark.cpp, CIValidations/CovarianceValidations.cpp, CIValidations/FitterValidations.cpp, CIValidations/SamplePDFValidations.cpp, CIValidations/SigmaVarValidations.cpp, CIValidations/TestOutputs/CovarianceOut.txt, CIValidations/pValueValidations.cpp, CMakeLists.txt, SamplesTutorial/SampleHandlerTutorial.cpp, SamplesTutorial/SampleHandlerTutorial.h, Tutorial/KinemDistributionTutorial.cpp, Tutorial/LLHScanTutorial.cpp, Tutorial/MCMCTutorial.cpp, TutorialConfigs/CovObjs/OscillationModel.yaml, TutorialConfigs/FitterConfig.yaml
Do not merge untill 2.1.0 tag is made
For more see: https://github.com/mach3-software/MaCh3/pull/494
=> breaking: Merge Generic and Osc cov

CIValidations/NuMCMCconversion.cpp
Simply no longer hardcode path for Config Osc and use new helper function
=> feat: Remove Config Hardcdoing

CIValidations/UnitTests/manager_tests.cpp
For more see:  https://github.com/mach3-software/MaCh3/pull/506
=> feat: Discrete Parameters

CIValidations/MaCh3CLI, cmake/Modules/mach3tutorial-config.cmake
mach3-tutorial --featuers didn't work propelry and MaCh3-CLI didn't work wiht unit testing. No it is fixed
=> bugfix: Cmake featuers

CIValidations/SamplePDFValidations.cpp, SamplesTutorial/SampleHandlerTutorial.cpp, SamplesTutorial/SampleHandlerTutorial.h
Simply run this funciton to make sure ti doesn't cause segfault etc.
=> feat: Print Integral into CI

CIValidations/CMakeLists.txt, CIValidations/MaCh3CLI, CIValidations/SplinePlotting/CMakeLists.txt, CIValidations/SplinePlotting/SplinePlotting.cpp
Add simple tool which should help with testing new spline interpolations
[SplinePlot.pdf](https://github.com/user-attachments/files/21262824/SplinePlot.pdf)
=> feat: Spline Interpolation Plotting

CIValidations/SplineValidations.cpp, CIValidations/TestOutputs/SplineMonoOut.txt
Dan long time ago added support for multiple samples within one BinnedSpline Object.
However, we didn't have a good way to validate it, as SampleHandler doesn't support this.
Hence, this PR is supposed to validate this 
This will work once https://github.com/mach3-software/MaCh3/pull/603 is merged
=> feat: Multiple Samples in SplineHandler CI

CIValidations/SplinePlotting/SplinePlotting.cpp
First merge https://github.com/mach3-software/MaCh3/pull/608
=> feat: More Spline plotting

CIValidations/MaCh3CLI
This will work after: https://github.com/mach3-software/MaCh3/pull/634
=> feat: More plotting validations
